### ISSUE TITLE
Create a web app of SysIdentPy

### ISSUE THREAD

**Issue by wilsonrljr** [wilsonrljr/sysidentpy#102]
SysIdentPy is a powerful Python package designed to make it easy for users to build NARMAX models from data. The package has been developed with the goal of providing an intuitive and user-friendly interface that can be easily used by both beginners and experts in the field. The complex part of the package is hidden behind the scenes, allowing users to focus on building models without worrying about the underlying complexity. However, despite the efforts made to simplify the package, there are still some users who are not comfortable working with Python code. 

To address this issue, the goal is to create a web app that will allow users to build dynamic models with ease, even if they have no experience with coding. The app will be built using Streamlit, a popular open-source framework that makes it easy to create web applications in Python. With the app, users will be able to upload their data, select the type of model they want to build, and customize the parameters according to their needs. The app will also provide a graphical interface that will allow users to visualize their data and model results.

The new feature will be created with the help of SysIdentPy development team. With this feature, users will be able to use SysIdentPy to build NARMAX models, even if they have no experience with coding.

**Comment by jceneziojr** [comment]
I'd like to work on it!

**Comment by wilsonrljr** [comment]
I'm closing this issue here because we finish the first version of the web app in a separate repository: https://github.com/jceneziojr/sysidentpygui

@FabioDavidF feel free to help us improve this work following the updates in the mentioned repository. I have some ideas of next steps, so if you are still interested we can talk about it
