### ISSUE TITLE
Hi, I would like to get a link to the companion book . I have searched online but to no avail! Thanx :)

### ISSUE THREAD

**Issue by ahmeddeladly** [wilsonrljr/sysidentpy#109]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wilsonrljr** [comment]
Hey @ahmeddeladly! Actually it's not done yet. I'll be updating the companion book in the following weeks and months. I should had made that clear in the changelog and in the Preface itself. I'll update the docs later explaining the idea behind the companion book.
