### ISSUE TITLE
Need to add extra feature in Narx model.

### ISSUE THREAD

**Issue by himanshupant24** [wilsonrljr/sysidentpy#110]
<html>
<body>
<div id=":ye" class="Ar Au Ao" style="display: block;"><div id=":ya" class="Am Al editable LW-avf tS-tW tS-tY" hidefocus="true" aria-label="Message Body" g_editable="true" role="textbox" aria-multiline="true" contenteditable="true" tabindex="1" style="direction: ltr; min-height: 343px;" spellcheck="false" aria-owns=":113" aria-controls=":113"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div dir="ltr"><div>1. The data looks like this. The "Need to forecast" line represents data to be forecasted by the Narx model.</div><div><br></div><div dir="auto">

Time_Stamp | Water_level | Rainfall | x1 | X2 | Met_office_Rain_forecast
-- | -- | -- | -- | -- | --
29/09/2020 13:45 | 10.2 | 0.5 | 2020 | 9 | NA
29/09/2020 14:00 | 7.8 | 0 | 2020 | 9 | NA
29/09/2020 14:15 | 8.3 | 1.3 | 2020 | 9 | NA
29/09/2020 14:30 | 23 | 2.6 | 2020 | 9 | NA
29/09/2020 14:45 | 11.4 | 0.35 | 2020 | 9 | NA
29/09/2020 15:00 | Need to forecast |   | 2020 | 9 | 1.25
29/09/2020 15:15 | Need to forecast |   | 2020 | 9 | 1.3
29/09/2020 15:30 | Need to forecast |   | 2020 | 9 | 1.4
29/09/2020 15:45 | Need to forecast |   | 2020 | 9 | 1.2
29/09/2020 16:00 | Need to forecast |   | 2020 | 9 | 0.89

<br></div><div>Met_office_Rain_forecast is the rain forecast data from the Met&nbsp;office. I want to forecast&nbsp;"Water_level" from the next time stamp (<span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">29/09/2020 15:00)&nbsp;&nbsp;</span><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">to the next 20.</span></div><div><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">&nbsp;</span></div><div><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">Let's say, If I have to forecast for the date "</span><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">29/09/2020 15:00",&nbsp; I am using&nbsp;<b>y_lag =3&nbsp;</b>which is&nbsp;<b>8.3,23 and 11.4</b>,&nbsp;<b>X_lag=2</b>&nbsp;which is&nbsp;<b>2.6, 0.35.</b></span></div><div><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;"><b></b>I also want to use X1, X2 and&nbsp;</span>rain forecast data (from the Met&nbsp;office) for that particular&nbsp;time stamp i.e&nbsp;<span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">"</span><span style="color: rgb(0, 0, 0); font-family: Calibri, sans-serif; font-size: 14.6667px; text-align: -webkit-right; white-space: nowrap;">29/09/2020 15:00".</span></div><div><br></div><div>The code you share with me:&nbsp;</div><div>narx_net = NARXNN(<br>&nbsp; &nbsp; ylag=2,<br>&nbsp; &nbsp; xlag=[[1, 2], [1, 2]], # defining lags for multiple inputs<br>&nbsp; &nbsp; basis_function=basis_function,<br></div><div><br></div><div>Here: xlag=[[1, 2], [1, 2]], I am not sure what 1 and 2 are representing. Can you please suggest what would be the values of xlag for my case? And do you have any comment on the presentation of data in the table.</div></div></div></div></div></div></div></div></div>
</body>
</html>

**Comment by wilsonrljr** [comment]
Hey @himanshupant24 , as I sent you by mail, the lag definition "[[1, 2], [1, 2]]" is the list of lags of each input. The first list, [1, 2], represents the lags of the first input x1 like x1(k-1) and x1(k-2). The second list is the same for the second input x2(k-1) and x2(k-2). If you have another input, x3 for example, the xlag should be something like this [[1, 2], [1, 2], [1, 2]].

You can check more details on the docs: 

http://sysidentpy.org/examples/defining_lags/
http://sysidentpy.org/examples/multiple_inputs_example/

I'll close this issue because I think this issue has been addressed I'll focusing on #111 to help you out.

If you have any questions, just let me know.
