### ISSUE TITLE
root_relative_squared_error function

### ISSUE THREAD

**Issue by miroder** [wilsonrljr/sysidentpy#114]
the root_relative_squared_error function right now is

    numerator = np.sum(np.square((yhat - y)))
    denominator = np.sum(np.square((yhat - np.mean(y, axis=0))))
    return np.sqrt(np.divide(numerator, denominator))

the denominator should be "np.sum(np.square((y- np.mean(y, axis=0))))" ?

Thx

**Comment by wilsonrljr** [comment]
Hey @miroder , that is correct. I fixed it and published in the new v0.3.2 version (which has some other changes). Thanks for catching that!
