### ISSUE TITLE
FutureWarning when passing a string as estimator (found in tutorial)

### ISSUE THREAD

**Issue by sebzuddas** [wilsonrljr/sysidentpy#124]

**Comment by wilsonrljr** [comment]
Hey @sebzudda! Are you getting an error? The future warning is just a warning saying that the method will be changing in a future version, but it's not an error

**Comment by sebzuddas** [comment]
Yes, my apologies. I didn't mean to post the comment.

**Comment by wilsonrljr** [comment]
Don't worry! No problem! The message its a little annoying, but that's the idea, actually, so the user can prepare for changes in the future version
