### ISSUE TITLE
Linear model structure

### ISSUE THREAD

**Issue by lucas-mior** [wilsonrljr/sysidentpy#130]
Hello, can sysidentpy be used to obtain a linear system from input data? If so, how?

**Comment by wilsonrljr** [comment]
Hey @lucas-mior . Yes, SysIdentPy can do that. To obtain a linear model structure, just make sure to set the degree of the basis function equal to 1. 

`basis_function = Polynomial(degree=1)`

You should notice that even in cases where the degree of the basis function is higher than 1, the final model might be linear. But, to make sure you are only looking for linear models, I suggest you to set the degree of the basis function equal to 1.
