### ISSUE TITLE
Example does not run

### ISSUE THREAD

**Issue by acristoffers** [wilsonrljr/sysidentpy#20]
O exemplo extended_least_squares.ipynb falha com esse erro:

```
0.5839138626779056
      Regressors Parameters         ERR
0        x1(k-2)     0.8886  0.74898574
1         y(k-1)     0.2710  0.06875041
2  x1(k-1)y(k-1)     0.0924  0.00403020
3         y(k-2)    -0.0411  0.00143946
4      x1(k-1)^2    -0.0575  0.00103367
5   y(k-2)y(k-1)     0.0619  0.00133295
6  x1(k-1)y(k-2)     0.0477  0.00065670
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Downloads/sysidentpy/examples/extended_least_squares.ipynb in <module>
     10
     11     model.fit(x_train, y_train)
---> 12     parameters[:, i] = list(model.theta)
     13
     14 sns.set()

ValueError: cannot copy sequence with size 7 to array axis with dimension 3
```

Todos os outros funcionam. Acho que podem adicionar "macOS OK" na lista.

**Comment by wilsonrljr** [comment]
Thanks for point out, @acristoffers. I just forget to add n_terms in the first model definition in this example. To run it before I push the fix, just add _n_terms=3_ in the first model instance (after "First we will train a model without the Extended Least Squares Algorithm for comparison purpose.")

`model = PolynomialNarmax(non_degree=2,
                         order_selection=True,
                         n_info_values=10,
                         n_terms=3,  # add this parameter
                         extended_least_squares=False,
                         ylag=2, xlag=2,
                         info_criteria='aic',
                         estimator='least_squares',
                         )`

**Comment by wilsonrljr** [comment]
I just push the fix to master. Once again thank you for point out. If you find any issues please tell us.
