### ISSUE TITLE
spatio-temporal identification

### ISSUE THREAD

**Issue by helonayala** [wilsonrljr/sysidentpy#42]
**Is your feature request related to a problem? Please describe.**
identification of PDEs

**Describe the solution you'd like**
spatio-temporal model creation and parameter estimation based only on data

**Describe alternatives you've considered**
the ERR can be used for the purpose too

**Additional context**
any plans on developing this feature? :)

**Comment by wilsonrljr** [comment]
Hi @helonayala. Thank's for your suggestion. Currently I'm working to bring Piece-Wise ARX models to the our package, but after the next update I can start working on it. It would be a great feature.

**Comment by wilsonrljr** [comment]
I'm closing this issue for now because I have no plans to implement this anytime soon because I'm focusing on some other features. If someone have the time to work on this I'll be glad to help and reopen this
