### ISSUE TITLE
I am unable to resolve  ModuleNotFoundError: No module named 'sysidentpy.model_structure_selection'

### ISSUE THREAD

**Issue by TeaCult** [wilsonrljr/sysidentpy#72]
Bug:
ModuleNotFoundError: No module named 'sysidentpy.model_structure_selection'

Steps/code to reproduce:
from sysidentpy.model_structure_selection import FROLS

Environment:
Version of the packages you are using
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sysidentpy in ./.local/lib/python3.6/site-packages (0.1.4.2)
Requirement already satisfied: torch>=1.7.1 in ./.local/lib/python3.6/site-packages (from sysidentpy) (1.10.0+cu113)
Requirement already satisfied: numpy>=1.17.3 in ./.local/lib/python3.6/site-packages (from sysidentpy) (1.19.5)
Requirement already satisfied: matplotlib>=3.1.0 in ./.local/lib/python3.6/site-packages (from sysidentpy) (3.3.4)
Requirement already satisfied: python-dateutil>=2.1 in ./.local/lib/python3.6/site-packages (from matplotlib>=3.1.0->sysidentpy) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib>=3.1.0->sysidentpy) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.6/site-packages (from matplotlib>=3.1.0->sysidentpy) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./.local/lib/python3.6/site-packages (from matplotlib>=3.1.0->sysidentpy) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in ./.local/lib/python3.6/site-packages (from matplotlib>=3.1.0->sysidentpy) (8.4.0)
Requirement already satisfied: dataclasses in ./.local/lib/python3.6/site-packages (from torch>=1.7.1->sysidentpy) (0.8)
Requirement already satisfied: typing-extensions in ./.local/lib/python3.6/site-packages (from torch>=1.7.1->sysidentpy) (3.7.4.3)
Requirement already satisfied: six in ./.local/lib/python3.6/site-packages (from cycler>=0.10->matplotlib>=3.1.0->sysidentpy) (1.15.0)

**Comment by wilsonrljr** [comment]
Hi @TeaCult!

sysidentpy.model_structure_selection.FROLS was introduced in version 0.1.7. You are using the 0.1.4.2 version. Update to the last version to use the new methods and algorithms. Check the changelog here to get more details about the new api: http://sysidentpy.org/changelog/v0.1.8.html

Let me know if everything works when you update.

**Comment by TeaCult** [comment]
Yes it works. I have installed python 3.7.12 and torch in pyenv. It solved the problem. Thank you.

**Comment by wilsonrljr** [comment]
Thats great! I'm closing this issue but feel free to open a new one if you had any problem!

**Comment by TeaCult** [comment]
ok ank you
