### ISSUE TITLE
Exception: Insufficient initial conditions elements!

### ISSUE THREAD

**Issue by rabiu42000** [wilsonrljr/sysidentpy#73]
I get this exception when i use model.fit(x_train, y_train, x_valid, y_valid)  for MetaMSS same with FROLS. What causes this kind of exception?
\sysidentpy\polynomial_basis\narmax.py", line 559, in _model_prediction
    raise Exception("Insufficient initial conditions elements!")

**Comment by wilsonrljr** [comment]
Hi @rabiu42000! 

Are you using the old api (from sysidentpy.polynomial_basis import MetaMSS)?

And how many samples x_valid and y_valid have?
