### ISSUE TITLE
add topic time-series-analysis

### ISSUE THREAD

**Issue by Beliavsky** [wilsonrljr/sysidentpy#76]
I suggest adding the topic `time-series-analysis`.

**Comment by wilsonrljr** [comment]
Hey @Beliavsky ! I'm pushing the new update in next days and I'll start working on better documentations about time series analysis. Do you have some specific topics in mind to suggest?

**Comment by wilsonrljr** [comment]
I'm closing this issue since no details were provided. Besides, I've started to work on a companion book for the package, so time series analysis will be covered anyway

**Comment by Beliavsky** [comment]
I was just suggesting to add `time-series-analysis` alongside other topics such as `system-indentification` in the About section, so that topic searches for `time-series-analysis` bring up the project.

**Comment by wilsonrljr** [comment]
I added as keyword in new v0.3.1 version. Thanks. I'll keep improving the topics and keywords
