### ISSUE TITLE
Neural NARX - Predicting without labels (forecasting) 

### ISSUE THREAD

**Issue by marcostx** [wilsonrljr/sysidentpy#79]
**Is your feature request related to a problem? Please describe.**
Enhancement of the predict method for Neural NARX in order to access forecasting scenarios where you don't have the labels (y). 

**Describe the solution you'd like**
Be able to use only the 'X_test' as input for the 'predict' method, adding a parameter like 'forecast_horizon' to express the number of steps to predict WITHOUT the actual labels. This is the scenario of a forecasting prediction.

**Comment by wilsonrljr** [comment]
Hi @marcostx, I'm pushing the new update and what you asked is possible in the new update. It was already possible, but the user had to do some work around in the code. Take a look at the air passenger benchmark example. There are some other features for Neural NARX, so take some time to check the changelog also. I'll be publishing the new version in pypi later this weekend
