### ISSUE TITLE
Installation Mac M1 chip

### ISSUE THREAD

**Issue by AntoineDubois** [wilsonrljr/sysidentpy#89]
Greeting,
Thank you for this amazing package.
I have a Mac 2022 with M1 chip and I failed to install the SysIdentPy.
Do you know how to circumvent the problem?
Thanks!

**Comment by wilsonrljr** [comment]
Hey @AntoineDubois, thanks! 

Are you getting any error message? Besides, how did you try to install it (virtual environment, python version)? 

I don't have a Mac, but I'll try my best to help you out with this issue.

**Comment by AntoineDubois** [comment]
I install sysidentpy with pip3. The installation is successful but my IDE (sublime and VScode) do not find the package.

**Comment by wilsonrljr** [comment]
Are you using a virtual environment? Seems like a problem where vscode is not pointing to the right environment/interpreter. 
Could you try to open a Python session in your terminal and import the package?

**Comment by AntoineDubois** [comment]
I think I had a problem with SublimeText 😅
It works now
Sorry for the time lost, and thank you for the quick reply

**Comment by wilsonrljr** [comment]
No problem at all! I'm glad you fix it. I'm closing this issue but feel free to open a new one if you find any other problem.
